-- Generated by tooling/scripts/generate-db-roles.ts. Do not edit by hand.
-- Retention role for Oremedia: used only by retentionSweepWorkflowV1 activities (DATABASE_URL_RETENTION, spec 17.5).
CREATE USER IF NOT EXISTS '__RETENTION_USER__'@'%';
REVOKE ALL PRIVILEGES, GRANT OPTION FROM '__RETENTION_USER__'@'%';
GRANT SELECT, DELETE ON `__DB_NAME__`.`agent_steps` TO '__RETENTION_USER__'@'%';
GRANT INSERT ON `__DB_NAME__`.`audit_events` TO '__RETENTION_USER__'@'%';
GRANT SELECT, UPDATE ON `__DB_NAME__`.`customer_voice_clusters` TO '__RETENTION_USER__'@'%';
GRANT SELECT, DELETE ON `__DB_NAME__`.`link_clicks` TO '__RETENTION_USER__'@'%';
GRANT SELECT, DELETE ON `__DB_NAME__`.`messages` TO '__RETENTION_USER__'@'%';
GRANT SELECT, DELETE ON `__DB_NAME__`.`metric_snapshots` TO '__RETENTION_USER__'@'%';
GRANT SELECT ON `__DB_NAME__`.`retention_policies` TO '__RETENTION_USER__'@'%';
GRANT SELECT, DELETE ON `__DB_NAME__`.`tool_invocations` TO '__RETENTION_USER__'@'%';
FLUSH PRIVILEGES;
