import { getTableName } from 'drizzle-orm';
import { MySqlTable } from 'drizzle-orm/mysql-core';
import * as schema from './schema';
import { INSERT_ONLY_TABLES } from './global-tables';

/**
 * Spec 6.1 immutability: the application DB role has no UPDATE/DELETE on insert-only tables. The SQL is generated
 * from the schema and INSERT_ONLY_TABLES so the grant list cannot drift (tooling/scripts/generate-db-roles.ts).
 */
export function generateRoleSql(dbName: string, user: string, host = '%'): string {
  const tables = Object.values(schema)
    .filter((v): v is MySqlTable => v instanceof MySqlTable)
    .map((t) => getTableName(t))
    .sort();
  const insertOnly = new Set(INSERT_ONLY_TABLES);
  const lines: string[] = [
    '-- Generated by tooling/scripts/generate-db-roles.ts. Do not edit by hand.',
    '-- Application role for Oremedia: full DML on mutable tables, INSERT/SELECT only on insert-only evidence tables (spec 6.1).',
    `CREATE USER IF NOT EXISTS '${user}'@'${host}';`,
    `REVOKE ALL PRIVILEGES, GRANT OPTION FROM '${user}'@'${host}';`,
  ];
  for (const t of tables) {
    if (insertOnly.has(t))
      lines.push(`GRANT SELECT, INSERT ON \`${dbName}\`.\`${t}\` TO '${user}'@'${host}';`);
    else lines.push(`GRANT SELECT, INSERT, UPDATE, DELETE ON \`${dbName}\`.\`${t}\` TO '${user}'@'${host}';`);
  }
  lines.push(
    `GRANT SELECT, INSERT, UPDATE ON \`${dbName}\`.\`__drizzle_migrations\` TO '${user}'@'${host}';`,
  );
  lines.push('FLUSH PRIVILEGES;');
  return lines.join('\n') + '\n';
}
