/**
 * Generates docs/contracts/events.md: the event catalogue (spec 7.7), the error codes (spec 7.2), and the public
 * surfaces of spec 7.6 (the /v1 REST route table with each route's procedure and scope, the API scope vocabulary and
 * the MCP tool subset) from the route tables themselves.
 */
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { MCP_TOOLS, allRestRoutes, createMcpRegistry } from '@oremedia/api';
import { ApiScope } from '@oremedia/contracts/access';
import { EVENT_TYPES } from '@oremedia/contracts/events';
import { ErrorCode } from '@oremedia/contracts/errors';

const events = Object.entries(EVENT_TYPES)
  .map(([type, v]) => `| \`${type}\` | ${v} |`)
  .join('\n');
const errors = ErrorCode.options.map((c) => `| \`${c}\` |`).join('\n');
const rest = allRestRoutes()
  .map(
    (r) =>
      `| \`${r.method}\` | \`${r.path.replace(/:([A-Za-z]+)/g, '{$1}')}\` | \`${r.procedure}\` | \`${r.scope}\` | ${r.summary} |`,
  )
  .join('\n');
const scopes = ApiScope.options.map((s) => `\`${s}\``).join(', ');
const registry = createMcpRegistry();
const mcp = MCP_TOOLS.map((t) => {
  const def = registry.get(t.name);
  return `| \`${t.name}\` | ${def?.effect ?? ''} | \`${def?.action ?? ''}\` | \`${t.scope}\` | ${t.brandScoped ? 'yes' : 'no'} |`;
}).join('\n');
const out = `# Contract catalogue (generated)

Generated by \`tooling/scripts/generate-contract-docs.ts\`. Do not edit by hand.

## Events (spec 7.7)

Every event is published in \`EventEnvelope\`; consumers are idempotent on \`eventId\`. Schema changes are additive;
a breaking change creates a new event type or schema version with dual publishing through a deprecation window.

| Event type | Schema version |
|---|---|
${events}

## Error codes (spec 7.2)

| Code |
|---|
${errors}

## Public REST API (spec 7.6)

Bearer authentication with an API client key (\`ak_...\`) or a session token; cookies are ignored. Each route calls
its tRPC procedure through the same middleware chain (tenant resolution, per-key scope, rate limit,
\`Idempotency-Key\` on every POST that mutates, audit). Errors use the envelope above with the matching HTTP status.
\`limit\` is clamped into [1, 200] (default 50). The OpenAPI document is \`docs/contracts/openapi.json\`.

| Method | Path | Procedure | Scope | Summary |
|---|---|---|---|---|
${rest}

## API client key scopes (spec 7.6)

${scopes}.

A query needs \`<area>:read\`, a mutation \`<area>:write\` (tRPC and REST alike; the area follows the router map). A key
with an empty scope list may read and not write. Scopes narrow a key; the service principal's grants and the policy
engine still decide every action.

## MCP tools (spec 7.6)

\`POST /mcp\`, JSON-RPC 2.0 over Streamable HTTP (\`initialize\`, \`ping\`, \`tools/list\`, \`tools/call\`), API client keys
only. Every call passes through the agent tool dispatcher as the key's service principal. No tool schedules or
publishes. A \`tools/call\` of a tool whose effect is not \`read\` requires the HTTP \`Idempotency-Key\` header, as a REST
POST does (each JSON-RPC message is its own HTTP request): the same key and arguments replay the stored result, other
arguments or another tool are \`IDEMPOTENCY_KEY_REUSED\`, a call in progress is \`CONFLICT\` with \`retryAfterMs\`.

| Tool | Effect | Policy action | Scope | Takes brandId |
|---|---|---|---|---|
${mcp}
`;
writeFileSync(path.resolve(process.cwd(), 'docs/contracts/events.md'), out);
console.error('wrote docs/contracts/events.md');
