/** Generates docs/contracts/events.md (event catalogue, spec 7.7) and tool-catalogue placeholder from the contracts package. */
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { EVENT_TYPES } from '@oremedia/contracts/events';
import { ErrorCode } from '@oremedia/contracts/errors';

const events = Object.entries(EVENT_TYPES)
  .map(([type, v]) => `| \`${type}\` | ${v} |`)
  .join('\n');
const errors = ErrorCode.options.map((c) => `| \`${c}\` |`).join('\n');
const out = `# Contract catalogue (generated)

Generated by \`tooling/scripts/generate-contract-docs.ts\`. Do not edit by hand.

## Events (spec 7.7)

Every event is published in \`EventEnvelope\`; consumers are idempotent on \`eventId\`. Schema changes are additive;
a breaking change creates a new event type or schema version with dual publishing through a deprecation window.

| Event type | Schema version |
|---|---|
${events}

## Error codes (spec 7.2)

| Code |
|---|
${errors}
`;
writeFileSync(path.resolve(process.cwd(), 'docs/contracts/events.md'), out);
console.error('wrote docs/contracts/events.md');
